'use client';

import { useRef, useState } from 'react';
import { Download, Upload, FileCode, Save, Trash2, ChevronDown } from '@/lib/icons';
import { useTokensStore, type Preset } from '@/components/playground/store/useTokensStore';
import { themeToCssVars } from '@/components/playground/lib/applyTokens';
import type { DesignTokens } from '@/types/design-tokens';

function downloadFile(filename: string, content: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function tokensToRootCss(tokens: DesignTokens): string {
  const lightVars = themeToCssVars(tokens.light);
  const darkVars = themeToCssVars(tokens.dark);

  const fmt = (vars: Record<string, string>, indent = '  ') =>
    Object.entries(vars)
      .map(([k, v]) => `${indent}${k}: ${v};`)
      .join('\n');

  return [
    '/* Propyte Design Tokens — generated by Design Playground */',
    ':root {',
    fmt(lightVars),
    '}',
    '',
    '[data-theme="dark"] {',
    fmt(darkVars),
    '}',
  ].join('\n');
}

export default function ExportImport() {
  const tokens = useTokensStore((s) => s.tokens);
  const presets = useTokensStore((s) => s.presets);
  const replaceAll = useTokensStore((s) => s.replaceAll);
  const savePreset = useTokensStore((s) => s.savePreset);
  const loadPreset = useTokensStore((s) => s.loadPreset);
  const deletePreset = useTokensStore((s) => s.deletePreset);

  const fileRef = useRef<HTMLInputElement>(null);
  const [presetName, setPresetName] = useState('');
  const [showPresets, setShowPresets] = useState(false);
  const [importError, setImportError] = useState('');

  const handleExportJson = () => {
    downloadFile(
      `propyte-tokens-${Date.now()}.json`,
      JSON.stringify(tokens, null, 2),
      'application/json',
    );
  };

  const handleExportCss = () => {
    downloadFile(
      `propyte-tokens-${Date.now()}.css`,
      tokensToRootCss(tokens),
      'text/css',
    );
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      try {
        const parsed = JSON.parse(ev.target?.result as string) as DesignTokens;
        if (!parsed.version || !parsed.light || !parsed.dark) {
          setImportError('JSON inválido: falta version, light o dark');
          return;
        }
        replaceAll(parsed);
        setImportError('');
      } catch {
        setImportError('Error al parsear JSON');
      }
    };
    reader.readAsText(file);
    e.target.value = '';
  };

  const handleSavePreset = () => {
    const name = presetName.trim();
    if (!name) return;
    savePreset(name);
    setPresetName('');
  };

  return (
    <div className="flex items-center gap-2 flex-wrap">
      {/* Export JSON */}
      <button
        type="button"
        onClick={handleExportJson}
        className="flex items-center gap-1.5 text-xs px-3 py-1.5 border border-neutral-200 rounded-md bg-white hover:bg-neutral-50 transition-colors"
        title="Exportar como JSON"
      >
        <Download size={13} />
        JSON
      </button>

      {/* Export CSS */}
      <button
        type="button"
        onClick={handleExportCss}
        className="flex items-center gap-1.5 text-xs px-3 py-1.5 border border-neutral-200 rounded-md bg-white hover:bg-neutral-50 transition-colors"
        title="Exportar como bloque :root { ... } CSS"
      >
        <FileCode size={13} />
        CSS
      </button>

      {/* Import */}
      <button
        type="button"
        onClick={() => fileRef.current?.click()}
        className="flex items-center gap-1.5 text-xs px-3 py-1.5 border border-neutral-200 rounded-md bg-white hover:bg-neutral-50 transition-colors"
        title="Importar JSON"
      >
        <Upload size={13} />
        Importar
      </button>
      <input
        ref={fileRef}
        type="file"
        accept=".json"
        className="hidden"
        onChange={handleImport}
        aria-label="Importar tokens JSON"
      />

      {/* Presets */}
      <div className="relative">
        <button
          type="button"
          onClick={() => setShowPresets((v) => !v)}
          className="flex items-center gap-1.5 text-xs px-3 py-1.5 border border-neutral-200 rounded-md bg-white hover:bg-neutral-50 transition-colors"
        >
          <Save size={13} />
          Presets {presets.length > 0 && `(${presets.length})`}
          <ChevronDown size={11} className={`transition-transform ${showPresets ? 'rotate-180' : ''}`} />
        </button>

        {showPresets && (
          <div className="absolute right-0 top-full mt-1 w-60 bg-white border border-neutral-200 rounded-md shadow-lg z-50 p-3">
            {/* Save new preset */}
            <div className="flex gap-1.5 mb-3">
              <input
                type="text"
                value={presetName}
                onChange={(e) => setPresetName(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSavePreset()}
                placeholder="Nombre del preset…"
                className="text-xs flex-1 px-2 py-1 border border-neutral-200 rounded focus:outline-none focus:border-neutral-400"
              />
              <button
                type="button"
                onClick={handleSavePreset}
                disabled={!presetName.trim()}
                className="text-xs px-2 py-1 bg-neutral-800 text-white rounded disabled:opacity-40 hover:bg-neutral-700 transition-colors"
              >
                Guardar
              </button>
            </div>

            {/* Preset list */}
            {presets.length === 0 ? (
              <p className="text-2xs text-neutral-400 text-center py-2">Sin presets guardados</p>
            ) : (
              <ul className="space-y-1 max-h-48 overflow-y-auto">
                {presets.map((preset: Preset) => (
                  <li key={preset.id} className="flex items-center gap-1.5 group">
                    <button
                      type="button"
                      onClick={() => { loadPreset(preset.id); setShowPresets(false); }}
                      className="flex-1 text-left text-xs truncate py-1 px-1.5 rounded hover:bg-neutral-100 transition-colors"
                      title={new Date(preset.createdAt).toLocaleString()}
                    >
                      {preset.name}
                    </button>
                    <button
                      type="button"
                      onClick={() => deletePreset(preset.id)}
                      className="opacity-0 group-hover:opacity-100 p-1 text-neutral-400 hover:text-red-500 transition-all"
                      aria-label={`Eliminar preset ${preset.name}`}
                    >
                      <Trash2 size={11} />
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}
      </div>

      {importError && (
        <span className="text-2xs text-red-500">{importError}</span>
      )}
    </div>
  );
}
